baseURL = 'https://EricSpencer00.github.io'
publicDir = "public"
languageCode = 'en-us'
title = 'Eric Spencer'
theme = "hugo-PaperMod"

[Params]
    avatar = "images/avatar.jpeg"
    [Params.profileMode]
        enabled = true
        title = "<Eric Spencer>"
        subtitle = "Eric Spencer, This site is currently under progress of being converted to Hugo"  

        imageUrl = "images/avatar.jpeg"
        imageTitle = "Profile Picture" # optional
        imageWidth = 240 # custom size
        imageHeight = 240 # custom size

        ShowSearch = true

  ShowImageInList = true
  ShowImageInPost = true


[[Params.socialIcons]]
    name = "github"
    url = "https://github.com/EricSpencer00"

[[Params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/EricSpencer00"

[[Params.socialIcons]]
    name = "Email"
    url = "mailto:ericspencer1450@gmail.com"

[[Params.socialIcons]]
    name = "CV"
    url = "resume/resume"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
    name = ""
    url = "/Resume/"
    weight = 10

[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2

[[menu.main]]
    name = "Recent"
    url = "/projects/recent/"
    parent = "Projects"
    weight = 4

[[menu.main]]
    name = "Old"
    url = "/projects/old/"
    parent = "Projects"
    weight = 3

[[menu.main]]
    name = "About Me"
    url= "/aboutMe/"
    weight = 1
[[menu.main]]
    name = "Miscellaneous"
    url = "/miscellaneous/"
    weight = 3