baseURL: "https://EricSpencer00.github.io"
publicDir: "public"
languageCode: "en-us"
title: "Eric Spencer"
theme: "hugo-PaperMod"

params:  # for post thumbnails and general settings
  ShowImageInList: true
  ShowImageInPost: true

Params:  # capital P needed for profileMode to work properly in some themes
  avatar: "images/avatar.jpeg"
  profileMode:
    enabled: true
    title: "<Eric Spencer>"
    subtitle: |
      <em>3rd year Computer Science Major at Loyola University Chicago</em><br>
      <strong>Loyola University Chicago | Class of 2026</strong><br>
      <strong>College of Arts and Sciences | Computer Science</strong><br>
      <strong>Quinlan School of Business | Information Systems</strong><br>
      <strong>espencer2 at luc dot edu</strong><br>
      <strong>ericspencer1450 at gmail dot com</strong>
    imageUrl: "images/avatar.jpeg"
    imageTitle: "Profile Picture"
    imageWidth: 240
    imageHeight: 240
  ShowSearch: true

  socialIcons:
    - name: "github"
      url: "https://github.com/EricSpencer00"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/EricSpencer00"
    - name: "Email"
      url: "mailto:ericspencer1450@gmail.com"
    - name: "CV"
      url: "resume/resume"

markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
    - name: "Resume"
      url: "/Resume/"
      weight: 10
    - name: "Projects"
      url: "/projects/"
      weight: 2
    - name: "Recent"
      url: "/projects/recent/"
      parent: "Projects"
      weight: 4
    - name: "Old"
      url: "/projects/old/"
      parent: "Projects"
      weight: 3
    - name: "About Me"
      url: "/aboutme/"
      weight: 1
    - name: "Miscellaneous"
      url: "/miscellaneous/"
      weight: 3
