baseURL = 'https://EricSpencer00.github.io'
languageCode = 'en-us'
title = 'Eric Spencer'
theme = "hugo-PaperMod"

[Params]
    avatar = "images/avatar.jpeg"
    [Params.profileMode]
        enabled = true
        title = "<Title>" # optional default will be site title
        subtitle = "This is subtitle"
        imageUrl = "<image link>" # optional
        imageTitle = "<title of image as alt>" # optional
        imageWidth = 120 # custom size
        imageHeight = 120 # custom size
        [[Params.profileMode.buttons]]
            name = "Archive"
            url = "/archive"
        [[Params.profileMode.buttons]]
            name = "Github"
            url = "https://github.com/EricSpencer00"

    [[Params.socialIcons]] # optional
        name = "<platform>"
        url = "<link>"
    [[Params.socialIcons]]
        name = "<platform 2>"
        url = "<link2>"

[[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2