baseURL = 'https://EricSpencer00.github.io'
languageCode = 'en-us'
title = 'Eric Spencer'
theme = "beautifulhugo"


[Params]
    avatar = "images/avatar.jpeg"

[[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2