baseURL = 'https://EricSpencer00.github.io'
languageCode = 'en-us'
title = 'Eric Spencer'
theme = "hugo-PaperMod"

[Params]
    avatar = "images/avatar.jpeg"
    [Params.profileMode]
        enabled = true
        title = "<Eric Spencer>" # optional default will be site title
        subtitle = "Eric Spencer"
        imageUrl = "images/avatar.jpeg"
        imageTitle = "Profile Picture" # optional
        imageWidth = 240 # custom size
        imageHeight = 240 # custom size
        [[Params.profileMode.buttons]]
            name = "Github"
            url = "https://github.com/EricSpencer00"
        [[Params.profileMode.buttons]]
            name = "LinkedIn"
            url = "https://linkedin.com/in/EricSpencer00"

[[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2