#!/usr/bin/env python3
"""Build the private, browser-side knowledge base for the site assistant.

The assistant does not call an application server.  Instead, this script reads
the finished public pages during deployment, turns their visible text into
small source-linked passages, and writes a static JavaScript data file.  The
browser ranks passages before it asks its locally running small language model
to answer.  Keeping the index in the build makes its "current" boundary
explicit: it is exactly the site that was built on that date.
"""

from __future__ import annotations

import html
import json
import re
from datetime import date
from html.parser import HTMLParser
from pathlib import Path

from build_og_images import published_pages

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "assets" / "data" / "site-knowledge.js"
BOOTSTRAP = (
    '<!-- site-assistant -->\n'
    '<script src="/assets/data/site-knowledge.js" data-site-knowledge></script>\n'
    '<script type="module" src="/assets/js/site-assistant.js" '
    'data-site-assistant></script>\n'
)
SKIP_PARTS = {".git", ".claude", "backup-site", "tests", "assets"}
SKIP_TAGS = {"script", "style", "noscript", "svg", "template"}
STUB = "<!-- redirect stub -->"


class VisibleText(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.parts: list[str] = []
        self.hidden = 0
        self.title: list[str] = []
        self.in_title = False

    def handle_starttag(self, tag: str, attrs) -> None:
        if tag in SKIP_TAGS:
            self.hidden += 1
        if tag == "title":
            self.in_title = True
        if tag in {"p", "div", "section", "article", "h1", "h2", "h3", "li", "br"}:
            self.parts.append(" ")

    def handle_endtag(self, tag: str) -> None:
        if tag in SKIP_TAGS and self.hidden:
            self.hidden -= 1
        if tag == "title":
            self.in_title = False
        if tag in {"p", "div", "section", "article", "h1", "h2", "h3", "li"}:
            self.parts.append(" ")

    def handle_data(self, data: str) -> None:
        if self.in_title:
            self.title.append(data)
        if not self.hidden:
            self.parts.append(data)


def compact(value: str) -> str:
    return re.sub(r"\s+", " ", html.unescape(value)).strip()


def chunks(text: str, limit: int = 900) -> list[str]:
    """Split at sentences where possible, with a small overlap for context."""
    sentences = re.split(r"(?<=[.!?])\s+", text)
    result: list[str] = []
    current = ""
    for sentence in sentences:
        sentence = sentence.strip()
        if not sentence:
            continue
        if current and len(current) + len(sentence) + 1 > limit:
            result.append(current)
            current = (current[-160:] + " " + sentence).strip()
        else:
            current = f"{current} {sentence}".strip()
    if current:
        result.append(current)
    return result


def published_html() -> list[tuple[str, Path]]:
    selected: list[tuple[str, Path]] = []
    seen: set[str] = set()
    for url, paths in published_pages().items():
        if url in seen:
            continue
        for path in paths:
            rel = path.relative_to(ROOT)
            if any(part in SKIP_PARTS for part in rel.parts):
                continue
            body = path.read_text(encoding="utf-8", errors="replace")
            if STUB not in body:
                selected.append((url, path))
                seen.add(url)
                break
    return selected


def index_pages() -> list[dict[str, str]]:
    index: list[dict[str, str]] = []
    for url, path in published_html():
        parser = VisibleText()
        parser.feed(path.read_text(encoding="utf-8", errors="replace"))
        title = compact(" ".join(parser.title)) or path.stem.replace("-", " ")
        text = compact(" ".join(parser.parts))
        for part in chunks(text):
            if len(part) > 70:
                index.append({"title": title, "url": url, "text": part})
    return index


def inject_bootstrap() -> int:
    changed = 0
    for _, path in published_html():
        source = path.read_text(encoding="utf-8", errors="replace")
        if 'data-site-assistant' in source or "</body>" not in source.lower():
            continue
        updated = re.sub(r"</body>", BOOTSTRAP + "</body>", source, count=1, flags=re.I)
        path.write_text(updated, encoding="utf-8")
        changed += 1
    return changed


def main() -> None:
    passages = index_pages()
    payload = {
        "updated": date.today().isoformat(),
        "passages": passages,
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "/* Generated by scripts/build_chatbot_knowledge.py. Do not hand-edit. */\n"
        f"window.ERIC_SITE_KNOWLEDGE = {json.dumps(payload, ensure_ascii=False, separators=(',', ':'))};\n",
        encoding="utf-8",
    )
    injected = inject_bootstrap()
    print(f"site assistant: indexed {len(passages)} passages; added widget to {injected} page(s)")


if __name__ == "__main__":
    main()
