name: Deploy Hugo to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Remove existing public folder (if exists)
        run: rm -rf public

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'v0.145.0'
          extended: true

      - name: Build Hugo Site
        run: |
          hugo --minify
          ls -la public  # Debugging: Check if public folder exists

      - name: Upload Artifact for Deployment
        if: success()
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy-to-gh-pages:
    needs: deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download Built Site
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
